def bienvenida():
    print("                                             _________________________")
    print("                                           /|_______________________  |")
    print("                                           ||                      |  |")
    print("                                           ||                      |  |Bienvenido")
    print("                                         _///_                     |  |")
    print("                                        / | | \                    |  |")
    print("                                       |   7   |                   |  |al")
    print("                                        \_---_/                    |  |")
    print("                                          |=|                      |  |")
    print("                                       __/|_|\__                   |  |Ahorcado")
    print("                                      /   ___   \                  |  |")
    print("                                     | | /■ ■\ | |                 |  |")
    print("                                     |_| \|||/ |_|                 |  |")
    print("                                     |||_______|||                 |  |")
    print("                                        |  ||  |                   |  |")
    print("                                        /  ||  \                   |  |")
    print("                                        |  ||  |                   |  |")
    print("                                        |  ||  |                   |  |")
    print("                                        |__||__|                   |__|")
    print("                                        |==||==|                  /    \ ")
    print("                                        \__/\__/                 /      \ ")
    print("                            ================================================")

def entrada():
    print("                                             _________________________")
    print("                                           /|_______________________  |")
    print("                                           ||                      |  |")
    print("                                           ||                      |  |")
    print("                                           \|                      |  |")
    print("                                            /                      |  |")
    print("                                           /                       |  |")
    print("                                           \                       |  |")
    print("                                           /\                      |  |")
    print("                                           \/                      |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |__|")
    print("                                                                  /    \ ")
    print("                                                                 /      \ ")
    print("                            ================================================")

def unaPerdida():
    print("                                             _________________________")
    print("                                           /|_______________________  |")
    print("                                           ||                      |  |")
    print("                                           ||                      |  |")
    print("                                         _///_                     |  |")
    print("                                        / | | \                    |  |")
    print("                                       |   7   |                   |  |")
    print("                                        \_---_/                    |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |__|")
    print("                                                                  /    \ ")
    print("                                                                 /      \ ")
    print("                            ================================================")

def dosPerdidas():
    print("                                             _________________________")
    print("                                           /|_______________________  |")
    print("                                           ||                      |  |")
    print("                                           ||                      |  |")
    print("                                         _///_                     |  |")
    print("                                        / | | \                    |  |")
    print("                                       |   7   |                   |  |")
    print("                                        \_---_/                    |  |")
    print("                                          |=|                      |  |")
    print("                                       __/|_|\__                   |  |")
    print("                                     /_|  ___  |_\                 |  |")
    print("                                       | /■ ■\ |                   |  |")
    print("                                       | \|||/ |                   |  |")
    print("                                       |_______|                   |  |")
    print("                                      /_/\_____\                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |__|")
    print("                                                                  /    \ ")
    print("                                                                 /      \ ")
    print("                            ================================================")

def tresPerdidas():
    print("                                             _________________________")
    print("                                           /|_______________________  |")
    print("                                           ||                      |  |")
    print("                                           ||                      |  |")
    print("                                         _///_                     |  |")
    print("                                        / | | \                    |  |")
    print("                                       |   7   |                   |  |")
    print("                                        \_---_/                    |  |")
    print("                                          |=|                      |  |")
    print("                                       __/|_|\__                   |  |")
    print("                                      /   ___  |_\                 |  |")
    print("                                     | | /■ ■\ |                   |  |")
    print("                                     |_| \|||/ |                   |  |")
    print("                                     |||_______|                   |  |")
    print("                                       /________\                  |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |__|")
    print("                                                                  /    \ ")
    print("                                                                 /      \ ")
    print("                            ================================================")

def cuatroPerdidas():
    print("                                             _________________________")
    print("                                           /|_______________________  |")
    print("                                           ||                      |  |")
    print("                                           ||                      |  |")
    print("                                         _///_                     |  |")
    print("                                        / | | \                    |  |")
    print("                                       |   7   |                   |  |")
    print("                                        \_---_/                    |  |")
    print("                                          |=|                      |  |")
    print("                                       __/|_|\__                   |  |")
    print("                                      /   ___   \                  |  |")
    print("                                     | | /■ ■\ | |                 |  |")
    print("                                     |_| \|||/ |_|                 |  |")
    print("                                     |||_______|||                 |  |")
    print("                                       /________\                  |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |  |")
    print("                                                                   |__|")
    print("                                                                  /    \ ")
    print("                                                                 /      \ ")
    print("                            ================================================")

def cincoPerdidas():
    print("                                             _________________________")
    print("                                           /|_______________________  |")
    print("                                           ||                      |  |")
    print("                                           ||                      |  |")
    print("                                         _///_                     |  |")
    print("                                        / | | \                    |  |")
    print("                                       |   7   |                   |  |")
    print("                                        \_---_/                    |  |")
    print("                                          |=|                      |  |")
    print("                                       __/|_|\__                   |  |")
    print("                                      /   ___   \                  |  |")
    print("                                     | | /■ ■\ | |                 |  |")
    print("                                     |_| \|||/ |_|                 |  |")
    print("                                     |||_______|||                 |  |")
    print("                                        |  ||_/                    |  |")
    print("                                        /  |                       |  |")
    print("                                        |  |                       |  |")
    print("                                        |  |                       |  |")
    print("                                        |__|                       |__|")
    print("                                        |==|                      /    \ ")
    print("                                        \__/                     /      \ ")
    print("                            ================================================")

def muerte():
    print("                                             _________________________")
    print("                                           /|_______________________  |       |\    /| ")
    print("                                           ||                      |  |       | \  / | ")
    print("                                           ||                      |  |       |  \/  | ")
    print("                                         _///_                     |  |            ")
    print("                                        / X X \                    |  |       |      | ")
    print("                                       |   7   |                   |  |       |      | ")
    print("                                        \_vvv_/                    |  |        \____/  ")
    print("                                          |=|                      |  |           ")
    print("                                       __/|_|\__                   |  |        _______  ")
    print("                                      /   ___   \                  |  |       |_____    ")
    print("                                     | | /■ ■\ | |                 |  |       |_______  ")
    print("                                     |_| \|||/ |_|                 |  |         ____   ")
    print("                                     |||_______|||                 |  |        |    |  ")
    print("                                        |  ||  |                   |  |        |---\  ")
    print("                                        /  ||  \                   |  |        |     \  ")
    print("                                        |  ||  |                   |  |         _____    ")
    print("                                        |  ||  |                   |  |           |    ")
    print("                                        |__||__|                   |__|           |     ")
    print("                                        |==||==|                  /    \         _____")
    print("                                        \__/\__/                 /      \       /     \ ")
    print("                            ======                     =====================    \_____/")
    print("                                  \                   /")
    print("                                   \                 /")
    print("                                    \               /")

def gano():
    print("                                             _________________________")
    print("                                           /|_______________________  |        ____")
    print("                                           ||                      |  |       /   ")
    print("                                           ||                      |  |      |    ---|")
    print("                  _///_                    \|                      |  |       \_____/ ")
    print("                 / ^ ^ \                    /                      |  |")
    print("                |   7   |                  /                       |  |         /\ ")
    print("                 \_\_/_/                   \                       |  |        /--\ ")
    print("                   | |                     /\                      |  |       /    \ ")
    print("                __/|_|\__                  \/                      |  |")
    print("               /   ○ ○   \                                         |  |        |\  |")
    print("              | |   7   | |                                        |  |        | \ |")
    print("              |_| \___/ |_|                                        |  |        |  \| ")
    print("              |||_______|||                                        |  |        ")
    print("                 |  ||  |                                          |  |        _____   | ")
    print("                 /  ||  \                                          |  |       /     \  | ")
    print("                 |  ||  |                                          |  |       \_____/  . ")
    print("                 |  ||  |                                          |  |")
    print("                 |__||__|                                          |__|")
    print("                 |==||==|                                         /    \ ")
    print("                 \__/\__/                                        /      \ ")
    print("              ====================                     =====================")
    print("                                  \                   /")
    print("                                   \                 /")
    print("                                    \               /")


#!!! ESTAS LINEAS ESTAN CONSERVADAS EN HOMENAJE A LOS PRIMEROS !!!
#!!! APRENDISAJES EN PROGRAMACIÓN Y PYTHON DE FEDENOODT !!!

"""def vida1():
    if vidasPerdidas == 1:
        dibujo.unaPerdida()

def vida2():
    if vidasPerdidas == 2:
        dibujo.dosPerdidas()

def vida3():
    if vidasPerdidas == 3:
        dibujo.tresPerdidas()

def vida4():
    if vidasPerdidas == 4:
        dibujo.cuatroPerdidas()

def vida5():
    if vidasPerdidas == 5:
        dibujo.cincoPerdidas()

def muerte():
    if vidasPerdidas == 6:
        dibujo.muerte()

def gano():
    if vidasPerdidas < 6:
        dibujo.gano()"""

dibujos = [entrada, unaPerdida, dosPerdidas, tresPerdidas, cuatroPerdidas, cincoPerdidas, muerte]